spring:
  application:
    name: student-micro
    
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root  
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        ddl-auto: update     
#spring.jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQL5Dialect

server:
  port: 1234
      